name: 'Build phars for all systems'
description: 'Build phars for the current commit'

runs:
  using: "composite"
  steps:
    - name: Install tools
      uses: ./.github/actions/tools

    - name: Compile phar Linux
      run: bin/castor castor:phar:linux
      shell: bash

    - name: Compile phar Darwin
      run: bin/castor castor:phar:darwin
      shell: bash

    - name: Compile phar Windows
      run: bin/castor castor:phar:windows
      shell: bash

    - name: Ensure PHAR is OK
      run: build/castor.linux-amd64.phar --version
      shell: bash
      working-directory: tools/phar
