name: 'Build the PHAR'
description: 'Build the PHAR for the current commit'

runs:
  using: "composite"
  steps:
    - name: Install tools
      uses: ./.github/actions/tools

    - name: Compile PHAR Linux
      run: vendor/bin/box compile -c box.linux-amd64.json
      shell: bash
      working-directory: tools/phar

    - name: Compile PHAR MacOS
      run: vendor/bin/box compile -c box.macos-amd64.json
      shell: bash
      working-directory: tools/phar

    - name: Compile PHAR Windows
      run: vendor/bin/box compile -c box.windows-amd64.json
      shell: bash
      working-directory: tools/phar

    - name: Ensure PHAR is OK
      run: build/castor.linux-amd64.phar --version
      shell: bash
      working-directory: tools/phar
