name: Build the PHAR

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  phar:
    name: Create a PHAR and upload it as an artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the PHAR
        uses: ./.github/actions/phar

      - name: Upload the Linux PHAR
        uses: actions/upload-artifact@v3
        with:
          name: 'castor.linux-amd64.phar'
          path: tools/phar/build/castor.linux-amd64.phar
          if-no-files-found: error

      - name: Upload the Darwin PHAR
        uses: actions/upload-artifact@v3
        with:
          name: 'castor.darwin-amd64.phar'
          path: tools/phar/build/castor.darwin-amd64.phar
          if-no-files-found: error

      - name: Upload the Windows PHAR
        uses: actions/upload-artifact@v3
        with:
          name: 'castor-windows-amd64.phar'
          path: tools/phar/build/castor.windows-amd64.phar
          if-no-files-found: error
