name: Check stub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  stub:
    name: Check there is no change to the stub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        uses: ./.github/actions/tools

      - name: Check if there is no change
        run: git diff --exit-code
        shell: bash
